### ISSUE TITLE
Test-projekt?

### ISSUE THREAD

**Issue by Judas1337** [Grynet/TemplateProject#3]
Hur i arkitekturen passar ett testprojekt in. Vad behöver ett IntegrationTest-projekt känna till och vad behöver ett UnitTest-projekt känna till?

**Comment by Grynet** [comment]
Integrationstestprojekt:
Då ett integrationstest syftar till att testa att system samverkar som förväntat så blir varje system i sig som en blackbox. Man är intresserad av vad som skickas in i kedjan av system och sen vad som kommer ut. Mer konkret så behöver man alltså känna till hur man anropar den första tjänsten i kedjan och hur man sen kontrollerar vad som kommer ut i slutet av systemkedjan.  

Unittest:
Unittest är ett så vitt begrepp men de unit tester jag har använt mig av i TemplateProject är regressionstester där varje unit är en modul i ett lager. Exempelvis så har jag ett testprojekt i templateproject som heter templateproject.regressiontest.sl.WebApi som är en avgränsning för det lagret. Inuti det projektet har jag sedan en testklass per controller. 

Hade jag hunnit lägga in fler tester så hade detta mönster fortsatt neråt. För Business logic layer hade jag haft ett projekt som heter TemplateProject.RegressionTest.Bll och sen en testklass för varje logikklass, exempelvis productlogic. 

Syftet med dessa tester är att verifiera av att intern logik för varje lager inte ändras när systemet vidareutvecklas och eftersom de är så snabba att köra (~1ms / test) så kan dessa köras vid continious integration.

Systemtest:
Utöver integrationstest och regressionstester för varje lager i system så skulle jag ha haft systemtester. Dessa tester är till för att se till att alla delarna i projektet fungerar ihop som förväntat. Som ett integrationstest för på systemnivå där systemkedjan byts ut mot en lagerkedja. 

Jag är däremot ingen testare så hur dessa hade satts upp på ett optimalt sätt vet jag inte. 

PS. Angående regressionstesterna för varje lager så borde dessa troligen heta TemplateProject.Bll.Regressiontest, TemplateProject.Sl.WebApi.Regressiontest osv för att visa den "hårda kopplingen" mellan projekten.
